examples/scrum/board/urls.py
from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter(trailing_slash=False)
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

examples/scrum/scrum/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from board.urls import router


urlpatterns = [
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url(r'^$', TemplateView.as_view(template_name='board/index.html')),
]

examples/scrum/board/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Sprint(models.Model):
    """Development iteration period."""
    
    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(blank=True, default='')
    end = models.DateField(unique=True)
    
    def __str__(self):
        return self.name or _('Sprint ending %s') % self.end


class Task(models.Model):
    """Unit of work to be done for the sprint."""
    
    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4
    
    STATUS_CHOICES = (
        (STATUS_TODO, _('Not Started')),
        (STATUS_IN_PROGRESS, _('In Progress')),
        (STATUS_TESTING, _('Testing')),
        (STATUS_DONE, _('Done')),
    )
    
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    sprint = models.ForeignKey(Sprint, blank=True, null=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, 
    	default=STATUS_TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL, 
    	null=True, blank=True)
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return self.name

examples/scrum/board/forms.py
import django_filters

from django.contrib.auth import get_user_model

from .models import Sprint, Task


User = get_user_model()


class NullFilter(django_filters.BooleanFilter):
    """Filter on a field set as null or not."""
    
    def filter(self, qs, value):
        if value is not None:
            return qs.filter(**{'%s__isnull' % self.name: value})
        return qs
        
        
class SprintFilter(django_filters.FilterSet):
    
    end_min = django_filters.DateFilter(name='end', lookup_type='gte')
    end_max = django_filters.DateFilter(name='end', lookup_type='lte')
    
    class Meta:
        model = Sprint
        fields = ('end_min', 'end_max', )


class TaskFilter(django_filters.FilterSet):
    
    backlog = NullFilter(name='sprint')
    
    class Meta:
        model = Task
        fields = ('sprint', 'status', 'assigned', 'backlog', )
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filters['assigned'].extra.update(
        	{'to_field_name': User.USERNAME_FIELD})

examples/scrum/board/views.py
from django.contrib.auth import get_user_model

from rest_framework import authentication, permissions, viewsets, filters

from .forms import SprintFilter, TaskFilter
from .models import Sprint, Task
from .serializers import SprintSerializer, TaskSerializer, UserSerializer


User = get_user_model()


class DefaultsMixin(object):
    """Default settings for view authentication, permissions, filtering
     and pagination."""
    
    authentication_classes = (
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,    
    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    paginate_by = 25
    paginate_by_param = 'page_size'
    max_paginate_by = 100
    filter_backends = (
        filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )


class SprintViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating sprints."""
    
    queryset = Sprint.objects.order_by('end')
    serializer_class = SprintSerializer
    filter_class = SprintFilter
    search_fields = ('name', )
    ordering_fields = ('end', 'name', )
    

class TaskViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating tasks."""
    
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_class = TaskFilter
    search_fields = ('name', 'description', )
    ordering_fields = ('name', 'order', 'started', 'due', 'completed', )
    
    
class UserViewSet(DefaultsMixin, viewsets.ReadOnlyModelViewSet):
    """API endpoint for listing users."""
    
    lookup_field = User.USERNAME_FIELD
    lookup_url_kwarg = User.USERNAME_FIELD
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer
    search_fields = (User.USERNAME_FIELD, )

examples/scrum/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Scrum Board</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'board/vendor/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'board/css/board.css' %}">
        <script type="text/html" id="home-template">
            <h2>Your Sprints</h2>
            <button class="add" type="submit">Add Sprint</button>
            <% if (sprints !== null) { %>
                <div class="sprints">
                    <% _.each(sprints.models, function (sprint) { %>
                        <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
                            <%- sprint.get('name') %> <br>
                            <span>DUE BY <%- sprint.get('end') %></span>
                        </a>
                    <% }); %>
                </div>
            <% } else { %>
                <h3 class="loading">Loading...</h3>
            <% } %>
        </script>
        <script type="text/html" id="login-template">
            <form action="" method="post">
                <label for="id_username">Username</label>
                <input id="id_username" type="text" name="username" maxlength="30" required />
                <label for="id_password">Password</label>
                <input id="id_password" type="password" name="password" required />
                <button type="submit">Login</button>
            </form>
        </script>
        <script type="text/html" id="header-template">
            <span class="title">Scrum Board Example</span>
            <% if (authenticated ) { %>
                <nav>
                    <a href="/" class="button">Your Sprints</a>
                    <a href="#" class="logout button">Logout</a>
                </nav>
            <% } %>
        </script>
        <script type="text/html" id="new-sprint-template">
            <form action="" method="post">
                <label for="id_name">Sprint Name</label>
                <input id="id_name" type="text" name="name" maxlength="100" required />
                <label for="id_end">End Date</label>
                <input id="id_end" type="date" name="end" />
                <label for="id_description">Description</label>
                <textarea id="id_description" name="description" cols="50"></textarea>
                <button class="cancel">Cancel</button>
                <button type="submit">Create</button>
            </form>
        </script>
        <script type="text/html" id="sprint-template">
            <% if (sprint !== null) { %>
                <% if (!sprint.invalid) { %>
                    <h2><%- sprint.get('name') %></h2>
                    <span class="due-date">Due <%- sprint.get('end') %></span>
                    <p class="description"><%- sprint.get('description') %></p>
                    <div class="tasks"></div>
                <% } else { %>
                    <h1>Sprint <%- sprint.get('id') %> not found.</h1>
                <% } %>
            <% } else { %>
                <h1 class="loading">Loading...</h1>
            <% } %>
        </script>
        <script type="text/html" id="status-template">
            <h4><%- title %></h4>
            <div class="list"></div>
            <% if (sprint === null) { %>
                <button class="add" type="submit">Add Task</button>
            <% } %>
        </script>
        <script type="text/html" id="new-task-template">
          <form class="add-task" action="" method="post">
              <label for="id_name">Task Name</label>
              <input id="id_name" type="text" name="name" maxlength="100" required />
              <label for="id_description">Description</label>
              <textarea id="id_description" name="description"></textarea>
              <button class="create" type="submit">Create</button>
              <button class="cancel" type="submit">Cancel</button>
          </form>
        </script>
        <script type="text/html" id="task-item-template">
            <%- task.get('name') %>
        </script>
        <script type="text/html" id="task-detail-template">
            <div data-field="name" class="name" contenteditable="true">
                <%- task.get('name') %>
            </div>
            <div data-field="description" class="description" contenteditable="true">
                <%- task.get('description') %>
            </div>
            <div class="with-label">
                <div class="label">Due:</div>
                <div data-field="due" class="due date" contenteditable="true">
                    <%- task.get('due') || empty %>
                </div>
            </div>
            <div class="with-label">
                <div class="label">Assigned To:</div>
                <div data-field="assigned" class="assigned" contenteditable="true">
                    <%- task.get('assigned') || empty %>
                </div>
            </div>
            <form>
                <button class="cancel" type="submit">Close</button>
                <button class="save hide" type="submit">Save</button>
            </form>
        </script>
    </head>
    <body>
    
        <div id="content"></div>
        
        <script src="{% static 'board/vendor/jquery.js' %}"></script>
        <script src="{% static 'board/vendor/underscore.js' %}"></script>
        <script src="{% static 'board/vendor/backbone.js' %}"></script>
        <script id="config" type="text/json">
            {
                "models": {},
                "collections": {},
                "views": {},
                "router": null,
                "apiRoot": "{% url 'api-root' %}",
                "apiLogin": "{% url 'api-token' %}"
            }
        </script>
        <script src="{% static 'board/js/app.js' %}"></script>
        <script src="{% static 'board/js/socket.js' %}"></script>
        <script src="{% static 'board/js/models.js' %}"></script>
        <script src="{% static 'board/js/views.js' %}"></script>
        <script src="{% static 'board/js/router.js' %}"></script>
    </body>
</html>